### PR TITLE
Create a sign up page

### LINKED ISSUE #125: Create a sign up page
As shown in #44 we need to create a Sing Up page where the user can sing up to receive emails about the events he's interested in, importing the information from the select page that will the implemented in #124 . 

This information will have to be sent to the server in a latter time.

### PR DESCRIPTION
**Pull request by TMTiagoT**
Fixes #125
Note: I tried for a time to not change the uplift to link the search and the sign up pages (without sucess) so i changed the uplift too (from selectPage.js to app.js).

### CODE REVIEW

**Comment by TMTiagoT** [comment]
check if the warnings were fixed

**Comment by matheushjs** [comment]
I think it's kinda crazy to lift up state all the way up to App.js. It might be better to keep state at the top class of a single page, not the top class of all the pages (App.js).

Passing state from a page to another can be done through GET parameters, for example. This way, pages are kept modularized.

I won't say your design is wrong, though. It's definitely do-able.

**Comment by FelSiq** [comment]
Warnings are fixed.
@matheushjs Should we discuss it deeper or can this branch be merged?

**Comment by FelSiq** [comment]
I found a little glitch about transferring **price** information between home page and the Sign Up page via "Cadastrar" button. 

All information are transferred just fine, but **both** price fields starts empty on the Sign Up page. 

Can you check this?

**Comment by matheushjs** [comment]
@FelSiq no problem in merging it, I didn't actually want to block the pull request, that's why I didn't use the "Request changes" feature.

**Pull request merged**
