### PR TITLE
Scrape a single event.

### LINKED ISSUE #65: Scrape a single event
Define one page to do that and get all the information possible from the event, comment your decisions in #64

### PR DESCRIPTION
**Pull request by matheushjs**
Fixes #65 

For testing, just run:
"python3 Robot.py"
It should print a bunch of events.

I have set up a basic structure for all scrapers that might be developed in the near future.

### CODE REVIEW

**Comment by martchellop** [comment]
I'm a little bit confused here, did you addressed #66 in this pull request?

**Comment by matheushjs** [comment]
I hadn't read the #66 issue, but yeah it seems like I addressed it.

That's surprising, though. The effort from going from #65 to #66 is very small.

**Comment by martchellop** [comment]
I didn't knew how much harder would be to go from #65 to #66 and I also didn't wanted a very big pull request, my intention was that we always do small chunks of increments

**Comment by matheushjs** [comment]
Done

**Pull request merged**
