### PR TITLE
Frontend dockerfile

### LINKED ISSUE #93: Put the frontend in a Container
Get the information from the /frontend file and make it run in a container.

### PR DESCRIPTION
**Pull request by FelSiq**
Fixes #93

Added a Dockerfile for the project front-end, alongside a README.md containing instructions.

### CODE REVIEW

**Comment by FelSiq** [comment]
Yes.

**Comment by matheushjs** [comment]
@FelSiq there are commits in your pull requests that were in Marcello's pull request.

Once I approved your pull request, Marcello's pull request was automatically accepted, even though I didn't want to approve/merge it.

Any idea on why Marcello's commits are on your branch?

**Comment by LTKills** [comment]
I believe the problem was on the creation of the branch, when I submitted [this PR](#100) I had the same problem. Fortunately for me the branch I used as a base was already merged so these problems didn't happen there. I believe we could let @martchellop submit his PR and we could work on possible conflicts afterwards.

**Comment by FelSiq** [comment]
@matheushjs It happened due to this strange [commit](https://github.com/martchellop/Entretenibit/commit/4b64f0a5c73763172957778709c9ded8a0ba61e1). I'm not sure why it ever happened, as this branch has nothing to do with the referenced one.

**Pull request merged**
