### PR TITLE
Show cards

### LINKED ISSUE #92: Show the cards for a event the user asked
Call the API done in #91 and display that information in the cards

### PR DESCRIPTION
**Pull request by martchellop**
Fixes #92 

I haven't test it in the container, only locally. In order to make it work now, we need to have both the server and the front end parts up and running. 

I've change the server port to 5000, if you want to test only that, now it's in __http://localhost:5000/eventsType?type=musical__ where "musical" it's the param for the query

I'm aware that we call the API every time the user types a letter and that isn't the ideal. Also, I've create a card to show when there's no event but it isn't looking too good. But I'm going to leave those changes for the next sprint.

### CODE REVIEW

**Comment by matheushjs** [comment]
Mate, why are you changing code standards when 3 other people have already done code adopting the current standards? I also prefer spaces than tabs, but it's a basic rule to follow the standards of the code you are touching. Also, this doesn't seem like a change that should be done monocratically without talking to the other people who developed this part of the code.

**Comment by martchellop** [comment]
I only changed from 4 spaces to 2 spaces. I have a small screen and it's hard to see nested HTML using 4 spaces

**Comment by BrunoGomesCoelho** [comment]
Waiting for Matheus's review to be addressed before accepting this as well.
For the space/tab comments, if the code base already uses 4, that should be what gets pushed to master, although nothing is stopping you from coding with 2 and then changing back.

**Comment by martchellop** [comment]
@BrunoGomesCoelho Remember monday when we discussed something like this? You were saying that you wanted to change some coding style in the robot because you had some tools that were saying so. It's basically the same thing, I have a plugin that saves to the default HTML format, which is 2 spaces in tabs (the reason, as said previously, it's because it get's really hard to understand nested HTML tags using 4 spaces). Since this tool changed the files I was coding, I tough it would be for the best to changed all the files to this format to not let us have files with separate styles.

**Comment by matheushjs** [comment]
I don't really mind if the coding style is changed or not, but I'm against arbitrarily changing it without having a good reason and support from other members of our group to do so. I can't imagine how messy this would become if everyone changed the code style to suit their own developing environments.

Anyway, another point I'd like to make is that it's harder to review your code when so many lines have changed. Supposing the coding style is going to be changed, I'd recommend placing it in another pull request so that we can more easily review your implementation of cards showing.

**Comment by BrunoGomesCoelho** [comment]
> @BrunoGomesCoelho Remember monday when we discussed something like this?

Yes, I remember, and I also remember that the consensus was that you guys didn't agree with me and that we were going to ignore my idea and follow only codacity's standards. 
Unless I remember wrongly, I don't see how the analogy holds in your favor.

**Comment by martchellop** [comment]
It wasn't arbitrary, I use the [HTML standard](https://github.com/xfiveco/html-coding-standards) and only noticed that because it was the first time I had to code for the interface.

And about reviewing the code. You can review the commit "show by type", since that's the last one before I changed all tabs

**Comment by martchellop** [comment]
@matheushjs What do you want for me to do? Close this pull request and open another one?

**Comment by BrunoGomesCoelho** [comment]
I guess other than the space discussion everything that in Matheus's review/codacy has been fixed;
Maybe a option would be to go back to 4 spaces for this pull request and then everything has been reviewed and could be accepted; the space discussion can them continue somewhere else with another pull request.

I don't see how I can merge only up to before the 
>  Changed code style 
commit so I think another commit undoing that one would be necessary @martchellop

**Comment by matheushjs** [comment]
I agree with @BrunoGomesCoelho above.

In my opinion, the best option is to undo the 'change code style' commit, and then on Monday we (at least me, @martchellop, @FelSiq and @TMTiagoT) can discuss the code style change to be done in another pull request.

The other option is to not undo anything and leave this to be discussed on Monday.

A no-option in my point of view is to accept the code style change without discussing with the group.

**Comment by martchellop** [comment]
Already changed back to before I changed the tabs. It's ready to be be merged

**Comment by TMTiagoT** [comment]
I fixed the codacy problems for now. But we really need to padronize this spaces/tabs (i prefer tabs, beacuse its easily done). I will not accept the pull request beacuse i dont now if who requested changes is satisfied.

**Comment by matheushjs** [comment]
Testing now

**Pull request merged**
