### PR TITLE
Add Cronjob for robot and e-mails

### LINKED ISSUE #162: Robot's crontab
Both web scrapper and email should run after a certain amount of time (every day for the scrapper and every week for the email).

The idea is to put this in the docker-compose to automatically run each one after that time

### PR DESCRIPTION
**Pull request by BrunoGomesCoelho**
Cronjob implemented and added to the system. Closes #162 

Things I found out during the pull request: Cronjob **does not** play nicely with Docker. It could even be argued that is even goes againt's the idea of having only one process per container.

With that in mind, maybe a better idea would have been to separate the crawling from the e-mail in different containers; then  [Tasker](https://github.com/opsxcq/tasker) could have been more easily used but I could not get it to work easily with our current setup.  Also, it would require some changes to the docker-compose. I am not at all proposing these major changes to the project at this stage, just logging my conclusions from searching the subject.

In any case, the final solution was the traditional linux cronjob system. The robot's Docker file was changed, to allow installation of cronjob and creating the necessary files for logging the jobs.

The crontab file was created, describing what to run  and when to run. What the current setup means:

- **We send-email every sunday at midnight**

- **Our scraper runs every day  at 20:00.** The reason for being this time is to give plenty of time for the scrapper to run before sending the e-mails at midnight on sundays

To test everything is working correctly, I have also added the following:

- **Every minute, print to the terminal "hello, cron seems to be working as intended".** This lets us test the crontab without having to mess around with the system's time.

So to test this pull request, just run `docker-compose build && docker-compose up` after pulling. Then wait at least 2 minutes from after the robot finished sending the e-mails and check the message "hello, cron seems to be working as intended" appears in the terminal.

PS: For the final release we can/should remove the print every minute job.

### CODE REVIEW

**Comment by matheushjs** [comment]
I believe you meant 22:00 for the robot?

Also, I'm confused regarding the line
```
* * * * * root echo "hello, cron seems to be working as intended" > /proc/1/fd/1 2>/proc/1/fd/2
```
because no time is specified. But at least it seems to be working as intended.

I've tested and it's working. I'll approve once the Codacy issues have been resolved.

**Comment by BrunoGomesCoelho** [comment]
> I believe you meant 22:00 for the robot?

Actually I did mean 20:00, 4 hours might be overkill but I didn't want for the e-mails to be sent during a update of the database.

> because no time is specified
 
That line means to run that command every minute. The asterisk means "every" in cron. As I said in the pull request, it is for testing if cron is working; when you run docker-up it should, every minute, print to the terminal running docker-compose "hello, cron seems to be working as intended".

Trying to fix codacy issues now.

**Comment by BrunoGomesCoelho** [comment]
> I thought it was 22 because of this line

Ops, you're right, will fix it now

**Comment by BrunoGomesCoelho** [comment]
Weird:
I think I have fixed the issue codacy was warning about, but for some weird reason it still flags that line. 
Anyone have any idea why?

Would ignoring this warning be a solution for you guys?

**Comment by matheushjs** [comment]
No clue.

Can you have multiple RUN statements within the Dockerfile? You could try splitting them all in different statements. Otherwise just deactivate such pattern on Codacy.

**Comment by BrunoGomesCoelho** [comment]
I ignored that issue only, but kept the pattern.

**Comment by matheushjs** [comment]
Ok, 1 sec and I'll merge

**Pull request merged**
