### PR TITLE
Create docker compose

### LINKED ISSUE #96: Create a Docker Compose
Put the containers from #93, #94 and #95 in a single using Docker Compose and make them work together. 

It's a good idea to use docker volumes to make the containers update itself when we change the code. See docker documentation about volumes for more information.

### PR DESCRIPTION
**Pull request by LTKills**
Added docker compose file and instructions on README.md

Fixes #96

### CODE REVIEW

**Comment by martchellop** [comment]
I strongly suggest to wait until merge request #109 is accepted, since it's going to change a few things and that's where it all comes together and the network has the work.

**Comment by BrunoGomesCoelho** [comment]
I got the error:

> ERROR: for frontend  Cannot start service frontend: driver failed programming external connectivity on endpoint entretenibit_frontend_1 (c095c33349a76f1db05d614bf44942e4999c568f33e010826a9edad156a958b7): Bind for 0.0.0.0:3000 failed: port is already allocated

Currently looking up what the problem is, will come back when I have a answer; did anyone else get this error?

**Comment by martchellop** [comment]
The problem it's that both frontend and server use port 3000. That was addressed in #109

**Comment by LTKills** [comment]
@BrunoGomesCoelho I believe this is not a docker-compose problem (am I right?). @martchellop should the problem be solved after #109 is merged?

**Comment by martchellop** [comment]
I don't know, I changed the server's port to 5000 in the pull request but if you hard coded the port to 3000 it's still not going to work

**Comment by matheushjs** [comment]
The port problem is fixed simply by changing 3000:3000 to 5000:5000.

However, I fixed it here and there were many other problems. I don't think the issue is solved until the command `docker-compose up` launches a functional application that integrates all 3 containers correctly.

**Comment by LTKills** [comment]
I'm not sure if the problems were related to the volumes. I removed them as I wasn't sure how they worked. `docker-compose up` is now working for me.

**Comment by matheushjs** [comment]
Don't worry about the environment variables. I've been testing our programs in 2 different computers, and one of them didn't have the '.env' file created.

**Comment by matheushjs** [comment]
`entretenibit_server_1 exited with code 0`

This isn't desirable, and is what I mentioned during lunch today.

That's simple to fix, though. Just change
```
  server:
    build: ./server
    ports:
      - "5000:5000"
```
To
```
  server:
    build: ./server
    entrypoint: yarn start dev
    ports:
      - "5000:5000"
```

**Comment by LTKills** [comment]
Changed as requested by @matheushjs. I may suggest you make changes yourself when they are simple as this one (commenting was probably even harder than fixing the problem yourself). Anyways, thanks for the help :smiley:

**Comment by matheushjs** [comment]
Yeah, I thought about that too, but I don't feel like changing someone's branch is polite. If I had decided to make any changes myself, I'd submit a separate pull request with your branch + my commit. That also felt overkill...

Anyways, approved.

**Pull request merged**
