### PR TITLE
Enhance webpage design

### LINKED ISSUE #164: Redo the site design
The website it's functional but not breath taken, some one probably should make this a 10/10 website design wise.

### PR DESCRIPTION
**Pull request by LTKills**
I believe the styling is much better. Still, I believe this PR is likely to cause some disagreement. I'm completely open for feedback and ideas, but please keep in mind we have a two-day deadline ahead (keep the changes modest!).

Fixes #164

### CODE REVIEW

**Comment by BrunoGomesCoelho** [comment]
There seems to be some possible React errors or warnings, could you have a look at them?

**Comment by BrunoGomesCoelho** [comment]
As a example of a error, the link to the page is not printed anymore when docker-compose is executed. I get the message:

frontend_1  | Compiled with warnings.
frontend_1  | 
frontend_1  | ./src/SelectPage/SelectPage.js
frontend_1  |   Line 6:   'LabelButtons' is defined but never used  no-unused-vars
frontend_1  |   Line 11:  'Link' is defined but never used          no-unused-vars
frontend_1  | 
frontend_1  | Search for the keywords to learn more about each warning.
frontend_1  | To ignore, add // eslint-disable-next-line to the line before.

If i manually type in `http://localhost:3000/home/`though it works.

**Comment by BrunoGomesCoelho** [comment]
About the actual design: I know each person will have a different opinion, but some things seem to be broken, ie:

There is a random red line in the middle of the screen:

screenshot from 2018-07-03 15-53-04

We can't read some text on the about page
screenshot from 2018-07-03 15-55-01

**Comment by LTKills** [comment]
That definetly is not working, that's not how the design should be. I'll take a look into it, hang in there

**Comment by BrunoGomesCoelho** [comment]
The warnings and errors are gone and it now shows the URL in the terminal!

But the red line and invisible text is still happening :/

**Comment by BrunoGomesCoelho** [comment]
Ooops, forget what I said!
It was actually due to my add block blocking the background image haha
I have turned it off and the site shows up correctly.

The only thing that seems kind of weird is the white space at the bottom of the page, specially on a large screen and in full screen mode:

screenshot from 2018-07-03 17-20-06

Other than that everything seems good and functional.

Now for style comments: the green text in the about us page seems kind of hard to read, is there any way of making it darker?

screenshot from 2018-07-03 17-21-50

**Comment by LTKills** [comment]
Oh! The space is due to image sizing, if you try it in smaller monitors (eg laptop) you can see that the white space gets smaller until it completely disappears! Responsiveness should be addressed in #145  so don't worry about it for now.

**Comment by BrunoGomesCoelho** [comment]
The ad-block thing will mostly only happen for my PC, I have Ublock Origin and I excessively block things so it breaks many sites. I don't think we need to worry about it :)

**Pull request merged**
